### .github/workflows/ci.yml


name: Terraform CI (Plan)

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: dev
            client_id: ${{ secrets.DEV_ARM_CLIENT_ID }}
            client_secret: ${{ secrets.DEV_ARM_CLIENT_SECRET }}
            subscription_id: ${{ secrets.DEV_ARM_SUBSCRIPTION_ID }}
            tenant_id: ${{ secrets.DEV_ARM_TENANT_ID }}
            tfstate_key: dev.tfstate
            tfstate_storage: ${{ secrets.DEV_TF_STATE_STORAGE }}

          - environment: prod
            client_id: ${{ secrets.PROD_ARM_CLIENT_ID }}
            client_secret: ${{ secrets.PROD_ARM_CLIENT_SECRET }}
            subscription_id: ${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
            tenant_id: ${{ secrets.PROD_ARM_TENANT_ID }}
            tfstate_key: prod.tfstate
            tfstate_storage: ${{ secrets.PROD_TF_STATE_STORAGE }}

    defaults:
      run:
        working-directory: terraform/environments/${{ matrix.environment }}

    env:
      ARM_CLIENT_ID: ${{ matrix.client_id }}
      ARM_CLIENT_SECRET: ${{ matrix.client_secret }}
      ARM_SUBSCRIPTION_ID: ${{ matrix.subscription_id }}
      ARM_TENANT_ID: ${{ matrix.tenant_id }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TF_STATE_RG }}" \
            -backend-config="storage_account_name=${{ matrix.tfstate_storage }}" \
            -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
            -backend-config="key=${{ matrix.tfstate_key }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Upload tfplan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-${{ matrix.environment }}
          path: terraform/environments/${{ matrix.environment }}/tfplan